# Generated by Django 6.0.7 on 2026-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('ADJ_IN', 'Adjustment In'), ('ADJ_OUT', 'Adjustment Out')], max_length=10),
        ),
    ]
